"""refactor user stations

Revision ID: 38f60d30e9f8
Revises: 20260412_0006
Create Date: 2026-04-15 08:40:33.595595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f60d30e9f8'
down_revision: Union[str, Sequence[str], None] = '20260412_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('can_receive_rides_for_non_payment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_profile_id'), 'driver_profile', ['id'], unique=False)
    op.create_index(op.f('ix_driver_profile_phone_number'), 'driver_profile', ['phone_number'], unique=True)
    op.create_index(op.f('ix_driver_profile_user_id'), 'driver_profile', ['user_id'], unique=False)
    op.drop_index('ix_call_sessions_provider_call_id', table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index('ix_call_events_call_session_id', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index('ix_call_recordings_call_session_id', table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index('ix_drivers_id', table_name='drivers')
    op.drop_index('ix_drivers_phone_number', table_name='drivers')
    op.drop_table('drivers')
    op.add_column('rides', sa.Column('dispatcher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rides_dispatcher_id'), 'rides', ['dispatcher_id'], unique=False)
    op.drop_constraint('rides_driver_id_fkey', 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['dispatcher_id'], ['id'])
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'])
    op.add_column('users', sa.Column('rules', sa.Boolean(), nullable=False))
    op.drop_column('users', 'dispatcher_stations_id')
    op.drop_column('users', 'driver_stations_id')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'can_receive_rides_for_non_payment')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'is_dispatcher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_dispatcher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_receive_rides_for_non_payment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('driver_stations_id', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('dispatcher_stations_id', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'rules')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key('rides_driver_id_fkey', 'rides', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_rides_dispatcher_id'), table_name='rides')
    op.drop_column('rides', 'dispatcher_id')
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='drivers_pkey')
    )
    op.create_index('ix_drivers_phone_number', 'drivers', ['phone_number'], unique=True)
    op.create_index('ix_drivers_id', 'drivers', ['id'], unique=False)
    op.create_table('call_recordings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kind', postgresql.ENUM('ORIGIN', 'DESTINATION', 'NOTES', name='recordingkind'), autoincrement=False, nullable=False),
    sa.Column('provider_recording_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name='call_recordings_call_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='call_recordings_pkey')
    )
    op.create_index('ix_call_recordings_call_session_id', 'call_recordings', ['call_session_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name='call_events_call_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='call_events_pkey')
    )
    op.create_index('ix_call_events_call_session_id', 'call_events', ['call_session_id'], unique=False)
    op.create_table('call_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_call_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('from_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('to_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('direction', postgresql.ENUM('INBOUND', 'OUTBOUND', name='calldirection'), autoincrement=False, nullable=False),
    sa.Column('current_state', postgresql.ENUM('INCOMING', 'ASK_ORIGIN', 'RECORD_ORIGIN', 'ASK_DESTINATION', 'RECORD_DESTINATION', 'ASK_NOTES', 'RECORD_NOTES', 'PROCESSING_ORDER', 'PLAY_SUMMARY', 'AWAIT_CONFIRMATION', 'SEARCHING_DRIVER_MESSAGE', 'CONNECT_DRIVER', 'CONNECT_CUSTOMER', 'FINISHED', 'FAILED', name='callstate'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'FINISHED', 'FAILED', name='callsessionstatus'), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ride_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_routing_action', postgresql.ENUM('NEW_ORDER', 'PLAY_SEARCHING_MESSAGE', 'CONNECT_TO_DRIVER', 'CONNECT_TO_CUSTOMER', 'PLAY_NO_ACTIVE_RIDE', 'PLAY_GENERIC_MESSAGE', name='routingaction'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='call_sessions_pkey')
    )
    op.create_index('ix_call_sessions_provider_call_id', 'call_sessions', ['provider_call_id'], unique=True)
    op.drop_index(op.f('ix_driver_profile_user_id'), table_name='driver_profile')
    op.drop_index(op.f('ix_driver_profile_phone_number'), table_name='driver_profile')
    op.drop_index(op.f('ix_driver_profile_id'), table_name='driver_profile')
    op.drop_table('driver_profile')
    # ### end Alembic commands ###
