"""add dispatcher_id to rides

Revision ID: 5ea81fa3e330
Revises: 20260426_0009
Create Date: 2026-04-26 11:00:40.701127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea81fa3e330'
down_revision: Union[str, Sequence[str], None] = '20260426_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dispatcher_profiles_user_id_key', 'dispatcher_profiles', type_='unique')
    op.drop_constraint('driver_profiles_user_id_key', 'driver_profiles', type_='unique')
    op.add_column('rides', sa.Column('dispatcher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rides_dispatcher_id'), 'rides', ['dispatcher_id'], unique=False)
    op.create_foreign_key(None, 'rides', 'users', ['dispatcher_id'], ['id'])
    op.drop_constraint('station_owner_profiles_user_id_key', 'station_owner_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('station_owner_profiles_user_id_key', 'station_owner_profiles', ['user_id'])
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_index(op.f('ix_rides_dispatcher_id'), table_name='rides')
    op.drop_column('rides', 'dispatcher_id')
    op.create_unique_constraint('driver_profiles_user_id_key', 'driver_profiles', ['user_id'])
    op.create_unique_constraint('dispatcher_profiles_user_id_key', 'dispatcher_profiles', ['user_id'])
    # ### end Alembic commands ###
