from enum import StrEnum


class RideStatus(StrEnum):
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    SEARCHING_DRIVER = "SEARCHING_DRIVER"
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED"
    DRIVER_ON_THE_WAY = "DRIVER_ON_THE_WAY"
    PICKED_UP = "PICKED_UP"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    FAILED = "FAILED"
